@(#)PROGRAM:XCTestSwiftSupport  PROJECT:XCTest-16082.1
@__C_Synthesized
XCTestError
NXCTestErrorCode
Code
NXCTestErrorCode
XCTest
XCTest
XCTSkip
XCTest
UnwrappingOptional
Issue
XCTest
ObservedErrorContext
__swift5_proto
raise
dictionaryWithObjects:forKeys:count:
message
initWithError:evaluatedExpression:message:filePath:lineNumber:
initWithExpectedValue:evaluatedExpression:message:filePath:lineNumber:
initWithException:evaluatedExpression:message:filePath:lineNumber:
initWithExplanation:evaluatedExpression:message:filePath:lineNumber:
reason
description
compactDescription
callStackReturnAddresses
init
.cxx_destruct
_installErrorObserver
_observeErrors
currentThread
threadDictionary
__swift_setObject:forKeyedSubscript:
__swift_objectForKeyedSubscript:
dealloc
type
objc
exception
unknown
/Library/Caches/com.apple.xbs/Sources/XCTest_Ponderosa/XCTest-16082.1/Sources/libXCTestSwiftSupport/XCTContext_SwiftExtensions.swift
Fatal error
XCTContext.runActivity(named:block:) failed because activities are disallowed in the current configuration.
XCTAssertNil failed: threw error "
XCTAssertNotNil failed: threw error "
XCTUnwrap failed: threw error "
XCTAssertTrue failed: threw error "
XCTAssertFalse failed: threw error "
XCTAssertEqual failed: threw error "
XCTAssertNotEqual failed: threw error "
XCTAssertGreaterThan failed: threw error "
XCTAssertGreaterThanOrEqual failed: threw error "
XCTAssertLessThan failed: threw error "
XCTAssertLessThanOrEqual failed: threw error "
XCTAssertThrowsError failed: throwing an unknown exception
XCTAssertThrowsError failed: throwing 
XCTAssertThrowsError failed: threw error "
XCTAssertThrowsError failed: did not throw an error
XCTAssertNoThrow failed: threw error "
v8@?0
com.apple.dt.xctest.swift-error-observation.enabled
com.apple.dt.xctest.swift-error-observation.last-observed-error
_TtCV6XCTestP33_B0397D3B80CBC8D7FB9A5B33AB2A74B820ObservedErrorContext5Issue
@16@0:8
v16@0:8
compactDescription
callStackReturnAddresses
T@"NSString",N,R
T@"NSArray",N,R
B16@0:8
@?16@0:8
@"<XCTSwiftErrorIssue>"8@?0
failed: caught error: "
_swift_willThrow
XCTest.Issue
init()
XCTSwiftErrorIssue
@"NSString"16@0:8
@"NSArray"16@0:8
_TtCs12_SwiftObject
__TEXT
swift_getObjCClassMetadata
So7NSErrorC
$s10Foundation21_BridgedStoredNSErrorP
$sSY
$s10Foundation18_ErrorCodeProtocolP
ySS_yptG
SS_ypt
So21XCTSkippedTestContextC
ySSypG
SDySSypG
_pIgzo_
_pSg
So8NSObjectC
SaySo8NSNumberCG
So7NSArrayC
So8NSThreadC
_nsError
Code
RawValue
_ErrorType
skippedTestContext
errorCode
errorCode
errorUserInfo
compactDescription
callStackReturnAddresses
error
